model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openrouter/openai/gpt-4o
      api_base: https://openrouter.ai/api/v1
      api_key: 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
      drop_params: true
